export const countries = [
  { language: "Arabic", flag: "dz", isoCode: "ar" },
  { language: "Bulgarian", flag: "bg", isoCode: "bg" },
  { language: "Chinese", flag: "cn", isoCode: "zh" },
  { language: "Chinese (Simplified)", flag: "cn", isoCode: "zh-hans" },
  { language: "Chinese (Traditional)", flag: "tw", isoCode: "zh-hant" },
  { language: "Czech", flag: "cz", isoCode: "cs" },
  { language: "Danish", flag: "dk", isoCode: "da" },
  { language: "Dutch", flag: "nl", isoCode: "nl" },
  { language: "English (American)", flag: "us", isoCode: "en-gb" },
  { language: "English (British)", flag: "gb", isoCode: "en-us" },
  { language: "Estonian", flag: "ee", isoCode: "et" },
  { language: "Finnish", flag: "fi", isoCode: "fi" },
  { language: "French", flag: "fr", isoCode: "fr" },
  { language: "German", flag: "de", isoCode: "de" },
  { language: "Greek", flag: "gr", isoCode: "el" },
  { language: "Hebrew", flag: "il", isoCode: "he" },
  { language: "Hungarian", flag: "hu", isoCode: "hu" },
  { language: "Indonesian", flag: "id", isoCode: "id" },
  { language: "Italian", flag: "it", isoCode: "it" },
  { language: "Japanese", flag: "jp", isoCode: "ja" },
  { language: "Korean", flag: "kr", isoCode: "ko" },
  { language: "Latvian", flag: "lv", isoCode: "lv" },
  { language: "Lithuanian", flag: "lt", isoCode: "lt" },
  { language: "Norwegian Bokmål", flag: "no", isoCode: "nb" },
  { language: "Polish", flag: "pl", isoCode: "pl" },
  { language: "Portuguese (Brazilian)", flag: "br", isoCode: "pt-br" },
  { language: "Portuguese (European)", flag: "pt", isoCode: "pt-pt" },
  { language: "Romanian", flag: "ro", isoCode: "ro" },
  { language: "Russian", flag: "ru", isoCode: "ru" },
  { language: "Slovak", flag: "sk", isoCode: "sk" },
  { language: "Slovenian", flag: "si", isoCode: "sl" },
  { language: "Spanish", flag: "es", isoCode: "es" },
  { language: "Swedish", flag: "se", isoCode: "sv" },
  { language: "Thai", flag: "th", isoCode: "th" },
  { language: "Turkish", flag: "tr", isoCode: "tr" },
  { language: "Ukrainian", flag: "ua", isoCode: "uk" },
  { language: "Vietnamese", flag: "vn", isoCode: "vi" }
];
